import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className={`min-h-screen flex flex-col`}>
          <Navbar />
          <main className='flex-1 h-full overflow-auto py-8 container mx-auto'>{children}</main>
          <Footer />
          <ToastContainer position="bottom-right" closeOnClick pauseOnHover />
        </div>
      </body>
    </html>
  )
}
